// angular-uploader/src/app/app.component.ts
import { Component, ViewEncapsulation } from '@angular/core';
// @ts-expect-error
import * as UC from '@uploadcare/uc-blocks';

UC.registerBlocks(UC);

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  encapsulation: ViewEncapsulation.ShadowDom
})
export class AppComponent {
  files: any[] = [];

  handleUploaderEvent(e: Event) {
    const { data: files } = (e as CustomEvent).detail;
    this.files = files;
  }
}

<div class="wrapper">
  <uc-uploader class="uploader-cfg uc-wgt-common"></uc-uploader>

  <uc-data-output
    (data-output)="handleUploaderEvent($event)"
    fire-event
    class="uploader-cfg uc-wgt-common"
  ></uc-data-output>
  <div class="output">
    <img
      *ngFor="let file of files"
      src="https://ucarecdn.com/{{ file.uuid }}/-/preview/-/scale_crop/400x400/"
      width="200"
    />
  </div>
</div>

// react-upload-blocks/src/App.js
import "./App.css";
import { useState } from "react";
import "./upload-blocks/uc-basic.css";
import "./upload-blocks/upload-blocks.js";

function App() {
  const [files, setFiles] = useState([]);
  const handleUploaderEvent = (e) => {
    const { data } = e.detail;
    setFiles(data);
  };
  return (
    <div className="wrapper">
      <div className="uploader">
        <uc-default-widget class="uc-wgt-common"/>
        <uc-data-output
          fire-event
          class="uc-wgt-common"
          onDataOutput={handleUploaderEvent}
        ></uc-data-output>
      </div>
      <div className="output">
        {files.map((file) => (
          <img
            key={file.uuid}
            src={`https://ucarecdn.com/${file.uuid}/-/preview/-/scale_crop/400x400/`}
            width="200"
          />
        ))}
      </div>
    </div>
  );
}

export default App;
