// examples/vue-uploader/minimal/src/App.vue
<script setup lang="ts">
import * as LR from "@uploadcare/blocks";

LR.registerBlocks(LR);
</script>

<template>
  <div>
    <lr-config ctx-name="my-uploader" pubkey="2b7f257e8ea0817ba746"></lr-config>
    <lr-file-uploader-minimal
      css-src="https://cdn.jsdelivr.net/npm/@uploadcare/blocks@0.30.0/web/lr-file-uploader-minimal.min.css"
      ctx-name="my-uploader"
      class="my-config"
    ></lr-file-uploader-minimal>
  </div>
</template>

// examples/react-uploader/minimal/src/App.js
import React from "react";
import * as LR from "@uploadcare/blocks";

LR.registerBlocks(LR);

export default function App() {
    return (
        <div>
            <lr-config
                ctx-name="my-uploader"
                pubkey="2b7f257e8ea0817ba746"
            ></lr-config>
            <lr-file-uploader-minimal
                css-src="https://cdn.jsdelivr.net/npm/@uploadcare/blocks@0.30.0/web/lr-file-uploader-minimal.min.css"
                ctx-name="my-uploader"
            ></lr-file-uploader-minimal>
        </div>
    );
}
