// examples/react-uploader/src/views/RegularView/RegularView.tsx
import React, { useEffect, useRef, useState } from 'react';

import * as LR from '@uploadcare/blocks';
import blocksStyles from '@uploadcare/blocks/web/lr-file-uploader-regular.min.css?url';
import { OutputFileEntry } from '@uploadcare/blocks';

import st from './RegularView.module.css';

LR.registerBlocks(LR);

export default function RegularView() {
  const [files, setFiles] = useState<OutputFileEntry<'success'>[]>([]);
  const ctxProviderRef = useRef<InstanceType<LR.UploadCtxProvider>>(null);

  useEffect(() => {
    const ctxProvider = ctxProviderRef.current;
    if (!ctxProvider) return;

    const handleChangeEvent = (e: LR.EventMap['change']) => {
      console.log('change event payload:', e);

      setFiles([...e.detail.allEntries.filter(f => f.status === 'success')] as OutputFileEntry<'success'>[]);
    };

    /*
      Note: Event binding is the main way to get data and other info from File Uploader.
      There plenty of events you may use.

      See more: https://uploadcare.com/docs/file-uploader/events/
     */
    ctxProvider.addEventListener('change', handleChangeEvent);
    return () => {
      ctxProvider.removeEventListener('change', handleChangeEvent);
    };
  }, [setFiles]);

  return (
    <div>
      <lr-config
        ctx-name="my-uploader"
        pubkey="2b7f257e8ea0817ba746"
        sourceList="local, url, camera, dropbox"
      ></lr-config>
      <lr-file-uploader-regular
        ctx-name="my-uploader"
        css-src={blocksStyles}
      ></lr-file-uploader-regular>
      <lr-upload-ctx-provider
        ctx-name="my-uploader"
        ref={ctxProviderRef}
      ></lr-upload-ctx-provider>

      <div className={st.previews}>
        {files.map((file) => (
          <div key={file.uuid}>
            <img
              className={st.previewImage}
              key={file.uuid}
              src={`${file.cdnUrl}/-/preview/-/resize/x400/`}
              width="200"
              height="200"
              alt={file.fileInfo.originalFilename || ''}
              title={file.fileInfo.originalFilename || ''}
            />

            <span className={st.previewTitle}>
              {file.fileInfo.originalFilename}, {formatSize(file.fileInfo.size)}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}

function formatSize(bytes: number | null) {
  if (!bytes) return '0 Bytes';

  const k = 1024;
  const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];

  const i = Math.floor(Math.log(bytes) / Math.log(k));

  return `${parseFloat((bytes / k ** i).toFixed(2))} ${sizes[i]}`;
}

// examples/vue-uploader/src/views/RegularView/RegularView.vue
<script>
import * as LR from '@uploadcare/blocks';
import blocksStyles from '@uploadcare/blocks/web/lr-file-uploader-regular.min.css?url';

LR.registerBlocks(LR);

export default {
  data() {
    return {
      blocksStyles,
      files: [],
    }
  },

  methods: {
    handleChangeEvent(e) {
      console.log('change event payload:', e);

      if (e.detail) {
        this.files = e.detail.allEntries.filter(f => f.status === 'success');
      }
    },
    formatSize(bytes) {
      if (!bytes) return '0 Bytes';

      const k = 1024;
      const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];

      const i = Math.floor(Math.log(bytes) / Math.log(k));

      return `${parseFloat((bytes / k ** i).toFixed(2))} ${sizes[i]}`;
    }
  },

  mounted() {
    /*
      Note: Event binding is the main way to get data and other info from File Uploader.
      There plenty of events you may use.

      See more: https://uploadcare.com/docs/file-uploader/events/
     */
    this.$refs.ctxProviderRef.addEventListener('change', this.handleChangeEvent);
  },

  beforeUnmount() {
    this.$refs.ctxProviderRef.removeEventListener('change', this.handleChangeEvent);
  }
}
</script>

<template>
  <div>
    <lr-config
      ctx-name="my-uploader"
      pubkey="2b7f257e8ea0817ba746"
      sourceList="local, url, camera, dropbox"
    ></lr-config>

    <lr-file-uploader-regular
      ctx-name="my-uploader"
      :css-src="blocksStyles"
    ></lr-file-uploader-regular>

    <lr-upload-ctx-provider
      ctx-name="my-uploader"
      ref="ctxProviderRef"
    ></lr-upload-ctx-provider>

    <div class="previews">
      <div
        v-for="file in files"
        :key="file.cdnUrl"
      >
        <img
          class="preview-image"
          :src="`${file.cdnUrl}/-/preview/-/resize/x400/`"
          width="200"
          height="200"
          :alt="file.fileInfo.originalFilename"
          :title="file.fileInfo.originalFilename"
        />

        <span class="preview-title">
          {{file.fileInfo.originalFilename}}, {{formatSize(file.fileInfo.size)}}
        </span>
      </div>
    </div>
  </div>
</template>

<style scoped>
.previews {
  display: flex;
  flex-direction: column;
  gap: 16px;
  width: 100%;
  margin-top: 32px;
}

.preview-image {
  display: block;
  object-fit: cover;
}

.preview-title {
  margin-top: 4px;
}
</style>
