// examples/angular-uploader/src/app/views/form-view/form-view.component.ts
import { Component } from '@angular/core';
import { JsonPipe } from '@angular/common';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { OutputFileEntry } from '@uploadcare/file-uploader';

import { FileUploaderComponent } from '../../components/file-uploader/file-uploader.component';

import MOCK_DATA from './mocks';

type FormType = {
  title: string;
  text: string;
  photos: OutputFileEntry[];
}

@Component({
  selector: 'form-view',
  imports: [
    FileUploaderComponent,
    ReactiveFormsModule,
    JsonPipe,
  ],
  templateUrl: './form-view.component.html',
  styleUrl: './form-view.component.scss'
})
export class FormViewComponent {
  title = new FormControl<string>(MOCK_DATA.title, { nonNullable: true });
  text = new FormControl<string>(MOCK_DATA.text, { nonNullable: true });
  photos = MOCK_DATA.photos;

  sentFormObject: FormType | null = null;

  theme: 'light' | 'dark' = document.body.classList.contains('theme--dark') ? 'dark' : 'light';

  handleFormSubmit(e: SubmitEvent) {
    e.preventDefault();

    this.sentFormObject = {
      title: this.title.value,
      text: this.text.value,
      photos: this.photos,
    };
  }

  handleThemeChange(e: Event) {
    if (!(e.target instanceof HTMLInputElement)) return;

    this.theme = e.target.checked ? 'light' : 'dark';

    this.updateDocumentTheme();
  }

  updateDocumentTheme() {
    document.body.classList.remove('theme--light');
    document.body.classList.remove('theme--dark');
    document.body.classList.add(`theme--${this.theme}`);
  }
}

<div class="root">
  <header class="header">
    <h1 class="view-title">New blog post</h1>

    <label class="theme-toggle">
      <input
        type="checkbox"
        [checked]="theme === 'light'"
        (change)="handleThemeChange($event)"
      >
      <img
        [src]="theme === 'light' ? 'assets/sun.png' : 'assets/moon.png'"
        width="18"
        height="18"
        alt="Switch to {{theme === 'light' ? 'dark' : 'light'}} theme"
      />
    </label>
  </header>

  @if (!sentFormObject) {
    <form class="form" (submit)="handleFormSubmit($event)">
      <div class="field">
        <label class="label" for="title">Title</label>
        <input
          class="input"
          type="text"
          id="title"
          [formControl]="title"
        />
      </div>

      <div class="field">
        <label class="label" for="text">Text</label>
        <textarea
          class="input"
          id="text"
          rows="10"
          [formControl]="text"
        ></textarea>
      </div>

      <div class="field">
        <p class="label">Photos</p>
        <file-uploader
          uploaderCtxName="my-uploader-1"
          uploaderClassName="file-uploader"
          [theme]="theme"
          [(files)]="photos"
        ></file-uploader>
      </div>

      <div class="field">
        <button class="button" type="submit">Publish</button>
      </div>
    </form>
  } @else {
    <pre class="result"><code>{{ sentFormObject | json }}</code></pre>
  }
</div>

// examples/react-uploader-adapter/src/views/FormView/FormView.tsx
import { OutputFileEntry } from '@uploadcare/file-uploader';
import { ChangeEventHandler, FormEventHandler, useCallback, useEffect, useState } from 'react';
import Toggle from 'react-toggle';
import 'react-toggle/style.css';

import sunImage from '../../assets/sun.png';
import moonImage from '../../assets/moon.png';

import FileUploader from '../../components/FileUploader/FileUploader';

import st from './FormView.module.scss';
import MOCK_DATA from './mocks';

type FormType = {
  title: string;
  text: string;
  photos: OutputFileEntry[];
}

export default function FormView() {
  const [title, setTitle] = useState<FormType['title']>(MOCK_DATA.title);
  const [text, setText] = useState<FormType['text']>(MOCK_DATA.text);
  const [photos, setPhotos] = useState<FormType['photos']>(MOCK_DATA.photos);

  const [sentFormObject, setSentFormObject] = useState<FormType | null>(null);

  const handleTitleChange = useCallback<ChangeEventHandler<HTMLInputElement>>(
    e => setTitle(e.target.value),
    [setTitle],
  );
  const handleTextChange = useCallback<ChangeEventHandler<HTMLTextAreaElement>>(
    e => setText(e.target.value),
    [setText],
  );
  const handleFormSubmit = useCallback<FormEventHandler<HTMLFormElement>>((e) => {
    e.preventDefault();
    setSentFormObject({
      title,
      text,
      photos,
    });
  }, [title, text, photos, setSentFormObject]);

  const [theme, setTheme] = useState<'light' | 'dark'>(document.body.classList.contains('theme--dark') ? 'dark' : 'light');

  const handleThemeChange = useCallback<ChangeEventHandler<HTMLInputElement>>(e => {
    setTheme(e.target.checked ? 'light' : 'dark');
  }, [setTheme]);

  useEffect(() => {
    document.body.classList.remove('theme--light');
    document.body.classList.remove('theme--dark');
    document.body.classList.add(`theme--${theme}`);
  }, [theme]);

  return (
    <div className={st.root}>
      <header className={st.header}>
        <h1 className={st.viewTitle}>New blog post</h1>
        <Toggle
          checked={theme === 'light'}
          className={st.themeToggle}
          icons={{
            checked: <img src={sunImage} width="16" height="16" />,
            unchecked: <img src={moonImage} width="14" height="14" />,
          }}
          onChange={handleThemeChange}
        />
      </header>

      <pre>{theme}</pre>

      {!sentFormObject && (
        <form className={st.form} onSubmit={handleFormSubmit}>
          <div className={st.field}>
            <label className={st.label} htmlFor="title">Title</label>
            <input
              className={st.input}
              type="text"
              id="title"
              value={title}
              onChange={handleTitleChange}
            />
          </div>

          <div className={st.field}>
            <label className={st.label} htmlFor="text">Text</label>
            <textarea
              className={st.input}
              id="text"
              rows={10}
              value={text}
              onChange={handleTextChange}
            />
          </div>

          <div className={st.field}>
            <label className={st.label}>Photos</label>
            <FileUploader
              uploaderClassName={st.fileUploader}
              files={photos}
              onChange={setPhotos}
              theme={theme}
            />
          </div>

          <div className={st.field}>
            <button className={st.button} type="submit">Publish</button>
          </div>
        </form>
      )}

      {!!sentFormObject && (
        <pre className={st.result}>
          <code>
            {JSON.stringify(sentFormObject, null, 2)}
          </code>
        </pre>
      )}
    </div>
  );
}
