// examples/react-uploader/src/views/MinimalView/MinimalView.tsx
import React, { useEffect, useRef, useState } from 'react';

import * as LR from '@uploadcare/blocks';
import { OutputFileEntry } from '@uploadcare/blocks';

import st from './MinimalView.module.css';

LR.registerBlocks(LR);

export default function MinimalView() {
  const [files, setFiles] = useState<OutputFileEntry<'success'>[]>([]);
  const ctxProviderRef = useRef<InstanceType<LR.UploadCtxProvider>>(null);

  useEffect(() => {
    const ctxProvider = ctxProviderRef.current;
    if (!ctxProvider) return;

    const handleChangeEvent = (e: LR.EventMap['change']) => {
      console.log('change event payload:', e);

      setFiles([...e.detail.allEntries.filter(f => f.status === 'success')] as OutputFileEntry<'success'>[]);
    };

    /*
      Note: Event binding is the main way to get data and other info from File Uploader.
      There plenty of events you may use.

      See more: https://uploadcare.com/docs/file-uploader/events/
     */
    ctxProvider.addEventListener('change', handleChangeEvent);
    return () => {
      ctxProvider.removeEventListener('change', handleChangeEvent);
    };
  }, [setFiles]);

  return (
    <div>
      <lr-config
        ctx-name="my-uploader-2"
        pubkey="a6ca334c3520777c0045"
      ></lr-config>
      <lr-file-uploader-minimal
        ctx-name="my-uploader-2"
      ></lr-file-uploader-minimal>
      <lr-upload-ctx-provider
        ctx-name="my-uploader-2"
        ref={ctxProviderRef}
      ></lr-upload-ctx-provider>

      <div className={st.previews}>
        {files.map((file) => (
          <div key={file.uuid} className={st.previewWrapper}>
            <img
              className={st.previewImage}
              key={file.uuid}
              src={`${file.cdnUrl}/-/preview/-/resize/x400/`}
              width="200"
              height="200"
              alt={file.fileInfo.originalFilename || ''}
              title={file.fileInfo.originalFilename || ''}
            />

            <p className={st.previewData}>
              {file.fileInfo.originalFilename}
            </p>
            <p className={st.previewData}>
              {formatSize(file.fileInfo.size)}
            </p>
          </div>
        ))}
      </div>
    </div>
  );
}

function formatSize(bytes: number | null) {
  if (!bytes) return '0 Bytes';

  const k = 1024;
  const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];

  const i = Math.floor(Math.log(bytes) / Math.log(k));

  return `${parseFloat((bytes / k ** i).toFixed(2))} ${sizes[i]}`;
}

// examples/angular-uploader/src/app/views/minimal-view/minimal-view.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  EventEmitter,
  Input,
  Output,
  ViewChild,
} from '@angular/core';
import * as LR from '@uploadcare/blocks';
import { OutputFileEntry } from '@uploadcare/blocks';

LR.registerBlocks(LR);

@Component({
  selector: 'minimal-view',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './minimal-view.component.html',
  styleUrl: './minimal-view.component.scss',
})
export class MinimalViewComponent {
  @Input() files: OutputFileEntry<'success'>[] = [];
  @Output() filesChange = new EventEmitter<OutputFileEntry<'success'>[]>();

  @ViewChild('ctxProvider', { static: true }) ctxProviderRef!: ElementRef<
    InstanceType<LR.UploadCtxProvider>
  >;

  ngOnInit() {
    /*
      Note: Event binding is the main way to get data and other info from File Uploader.
      There plenty of events you may use.

      See more: https://uploadcare.com/docs/file-uploader/events/
     */
    this.ctxProviderRef.nativeElement.addEventListener(
      'change',
      this.handleChangeEvent,
    );
  }

  ngOnDestroy() {
    this.ctxProviderRef.nativeElement.removeEventListener(
      'change',
      this.handleChangeEvent,
    );
  }

  handleChangeEvent = (e: LR.EventMap['change']) => {
    console.log('change event payload:', e);

    this.files = e.detail.allEntries.filter(f => f.status === 'success') as OutputFileEntry<'success'>[];
  };

  formatSize = (bytes: number | null) => {
    if (!bytes) return '0 Bytes';

    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];

    const i = Math.floor(Math.log(bytes) / Math.log(k));

    return `${parseFloat((bytes / k ** i).toFixed(2))} ${sizes[i]}`;
  };
}

<lr-config
  ctx-name="my-uploader"
  pubkey="a6ca334c3520777c0045"
></lr-config>
<lr-file-uploader-minimal
  ctx-name="my-uploader"
></lr-file-uploader-minimal>
<lr-upload-ctx-provider
  ctx-name="my-uploader"
  #ctxProvider
></lr-upload-ctx-provider>

<div class="previews">
  @for (file of files; track file.cdnUrl) {
    <div class="preview-wrapper">
      <img
        class="preview-image"
        src="{{ file.cdnUrl + '/-/preview/-/resize/x400/' }}"
        height="200"
        width="200"
        [alt]="file.fileInfo.originalFilename"
        [title]="file.fileInfo.originalFilename"
      />

      <p class="preview-data">
        {{ file.fileInfo.originalFilename }}
      </p>
      <p class="preview-data">
        {{ formatSize(file.fileInfo.size) }}
      </p>
    </div>
  }
</div>
