// examples/svelte-uploader/src/App.svelte
<script>
  /*
   * Use minified version because codesandbox can't bundle raw css with relative imports.
   * It's better to use '@uploadcare/uc-blocks/blocks/themes/lr-basic/index.css' instead
   */
  import "@uploadcare/uc-blocks/web/lr-basic.min.css";
  import * as LR from "@uploadcare/uc-blocks";

  LR.registerBlocks(LR);

  let files = [];
  function handleUploaderEvent(e) {
    const { data } = e.detail;
    files = data;
  }
</script>

<div class="wrapper">
  <lr-file-uploader-regular class="uploader-cfg lr-wgt-common" />

  <lr-data-output
    fire-event
    class="uploader-cfg lr-wgt-common"
    on:data-output={handleUploaderEvent}
  />
  <div class="output">
    {#each files as file}
      <img
        src="https://ucarecdn.com/{file.uuid}/-/preview/-/scale_crop/400x400/"
        width="200"
        alt="Uploadcare uploaded file"
      />
    {/each}
  </div>
</div>

<style>
  .wrapper {
    display: flex;
    flex-direction: column;
    grid-gap: 32px;
    padding: 32px;
  }
  .output {
    display: grid;
    grid-gap: 8px;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    width: 100%;
    max-width: 1000px;
  }
  .uploader-cfg {
    --ctx-name: "uploader";

    /* DO NOT FORGET TO USE YOUR OWN PUBLIC KEY */
    --cfg-pubkey: "demopublickey";
    --cfg-multiple: 1;
    --cfg-confirm-upload: 1;
    --cfg-img-only: 0;
    --cfg-accept: "";
    --cfg-store: 1;
    --cfg-camera-mirror: 0;
    --cfg-source-list: "local, url, camera, dropbox, gdrive";
    --cfg-max-files: 10;
  }
</style>

// examples/react-uploader/src/App.js
import { useState, useCallback, useRef, useEffect } from "react";
import * as LR from "@uploadcare/blocks";

/*
 * Order of css imports is important. User styles should be loaded after the main theme
 * Or config selector should be more specific.
 *
 * Use minified version because codesandbox can't bundle raw css with relative imports.
 * It's better to use '@uploadcare/blocks/blocks/themes/lr-basic/index.css' instead
 */
import "@uploadcare/blocks/web/lr-basic.min.css";
import st from "./App.module.css";

LR.registerBlocks(LR);

function App() {
  let dataOutputRef = useRef();
  const [files, setFiles] = useState([]);
  const handleUploaderEvent = useCallback((e) => {
    const { data } = e.detail;
    setFiles(data);
  }, []);

  useEffect(() => {
    let el = dataOutputRef.current;
    el.addEventListener("lr-data-output", handleUploaderEvent);
    return () => {
      el.removeEventListener("lr-data-output", handleUploaderEvent);
    };
  }, [handleUploaderEvent]);

  const classNames = ["lr-wgt-common", st.uploaderCfg].join(" ");

  return (
    <div className={st.wrapper}>
      <lr-file-uploader-regular class={classNames}></lr-file-uploader-regular>

      <lr-data-output
        ref={dataOutputRef}
        use-event
        class={classNames}
        onEvent={handleUploaderEvent}
      ></lr-data-output>

      <div className={st.output}>
        {files.map((file) => (
          <img
            key={file.uuid}
            src={`https://ucarecdn.com/${file.uuid}/-/preview/-/scale_crop/400x400/`}
            width="200"
            alt="Preview"
          />
        ))}
      </div>
    </div>
  );
}

export default App;
