// examples/svelte-uploader/app-example/src/App.svelte
<script>
  import sunImage from './assets/sun.png';
  import moonImage from './assets/moon.png';

  import FileUploader from './lib/FileUploader/FileUploader.svelte';

  import MOCK_DATA from './mocks';

  let title = MOCK_DATA.title;
  let text = MOCK_DATA.text;
  let photos = MOCK_DATA.photos;

  let sentFormObject = null;

  const handleFormSubmit = e => {
    e.preventDefault();
    sentFormObject = {
      title,
      text,
      photos,
    };
  }

  let theme = 'light';

  const handleThemeChange = e => {
    theme = e.target.checked ? 'light' : 'dark';
  }

  $: {
    document.body.classList.remove('theme--light');
    document.body.classList.remove('theme--dark');
    document.body.classList.add(`theme--${theme}`);
  }
</script>

<div class="app">
  <header class="header">
    <h1 class="view-title">New blog post</h1>

    <label class="theme-toggle">
      <input
        type="checkbox"
        checked={theme === 'light'}
        on:change={handleThemeChange}
      >
      <img
        src={theme === 'light' ? sunImage : moonImage}
        width="18"
        height="18"
        alt={`Switch to ${theme === 'light' ? 'dark' : 'light'} theme`}
      />
    </label>
  </header>

  {#if !sentFormObject}
    <form class="form" on:submit={handleFormSubmit}>
      <div class="field">
        <label class="label" for="title">Title</label>
        <input
          class="input"
          type="text"
          id="title"
          bind:value={title}
        />
      </div>

      <div class="field">
        <label class="label" for="text">Text</label>
        <textarea
          class="input"
          id="text"
          rows={10}
          bind:value={text}
        ></textarea>
      </div>

      <div class="field">
        <p class="label">Photos</p>
        <FileUploader
          uploaderClassName="file-uploader"
          bind:files={photos}
          theme={theme}
        />
      </div>

      <div class="field">
        <button class="button" type="submit">Publish</button>
      </div>
    </form>
  {:else}
    <pre class="result"><code>{JSON.stringify(sentFormObject, null, 2)}</code></pre>
  {/if}
</div>

<style lang="scss">
  .app {
    padding: 16px 24px;
    max-width: 480px;
    margin: 0 auto;
  }

  .header {
    margin-bottom: 48px;
    display: flex;
    justify-content: space-between;
  }

  .theme-toggle {
    padding: 6px;
    box-shadow: 0 0 16px 0 var(--ui-control-box-shadow-color);
    background-color: var(--ui-control-background-color);
    border: 1px solid var(--ui-control-border-color-default);
    border-radius: 100%;
    cursor: pointer;
    user-select: none;

    &:hover {
      background-color: var(--ui-control-background-color);
      border: 1px solid var(--ui-control-border-color-default);
      outline: 2px solid var(--ui-control-outline-color-focus);
    }

    input {
      display: none;
    }

    img {
      display: block;
    }
  }

  .view-title {
    margin: 0;
    font-size: 16px;
    font-weight: 400;
    color: var(--ui-text-color);
  }

  .input {
    box-sizing: border-box;
    width: 100%;
    padding: 8px 12px;
    font-family: monospace;
    font-size: 16px;
    border: 1px solid var(--ui-control-border-color-default);
    border-radius: 8px;
    background: var(--ui-control-background-color);
    box-shadow: 0 0 16px 0 var(--ui-control-box-shadow-color);
    color: var(--ui-control-text-color);

    &:focus {
      outline: 3px solid var(--ui-control-outline-color-focus);
      border-color: var(--ui-control-border-color-focus);
    }

    // trying to prevent scrollbar overflowing textarea borders =/
    &::-webkit-scrollbar-corner {
      display: none;
    }
  }

  .field {
    margin-top: 24px;

    &:last-child {
      margin-top: 48px;
    }
  }

  .label {
    position: relative;
    z-index: 1;
    display: block;
    margin-bottom: 8px;
    color: var(--ui-text-color);
  }

  .button {
    font-size: 16px;
    font-family: monospace;
    line-height: 1;
    padding: 10px 12px;
    border: 1px solid var(--ui-control-border-color-default);
    border-radius: 8px;
    box-shadow: 0 0 16px 0 var(--ui-control-box-shadow-color);
    background: var(--ui-action-button-background);
    color: var(--ui-action-button-text-color);
    cursor: pointer;

    &:hover, &:focus {
      outline: 3px solid var(--ui-control-outline-color-focus);
    }

    &:active {
      border-color: var(--ui-control-border-color-focus);
    }
  }

  .result {
    font-size: 14px;
    line-height: 18px;
    font-family: monospace;
    white-space: pre-wrap;
  }

  /*
    Note: Localization of File Uploader is done via CSS variables.
    You can change any piece of text of File Uploader this way.

    See more: https://uploadcare.com/docs/file-uploader/localization/
   */
  :global(.file-uploader) {
    --l10n-locale-name: 'en-US';

    --l10n-photo__one: 'photo';
    --l10n-photo__many: 'photos';
    --l10n-photo__other: 'photos';

    --l10n-upload-file: 'Upload photo';
    --l10n-upload-files: 'Upload photos';
    --l10n-choose-file: 'Choose photo';
    --l10n-choose-files: 'Choose photos';
    --l10n-drop-files-here: 'Drop photos here';
    --l10n-select-file-source: 'Select photo source';
    --l10n-edit-image: 'Edit photo';
    --l10n-no-files: 'No photos selected';
    --l10n-caption-edit-file: 'Edit photo';
    --l10n-files-count-allowed: 'Only {{count}} {{plural:photo(count)}} allowed';
    --l10n-files-max-size-limit-error: 'Photo is too big. Max photo size is {{maxFileSize}}.';
    --l10n-header-uploading: 'Uploading {{count}} {{plural:photo(count)}}';
    --l10n-header-succeed: '{{count}} {{plural:photo(count)}} uploaded';
    --l10n-header-total: '{{count}} {{plural:photo(count)}} selected';
  }
</style>

// examples/react-uploader/src/App.tsx
import { OutputFileEntry } from '@uploadcare/blocks';
import { ChangeEventHandler, FormEventHandler, useCallback, useEffect, useState } from 'react';
import Toggle from 'react-toggle';
import 'react-toggle/style.css';

import sunImage from './assets/sun.png';
import moonImage from './assets/moon.png';

import FileUploader from './FileUploader/FileUploader';

import st from './App.module.scss';
import MOCK_DATA from './mocks';

type FormType = {
  title: string;
  text: string;
  photos: OutputFileEntry[];
}

export default function App() {
  const [title, setTitle] = useState<FormType['title']>(MOCK_DATA.title);
  const [text, setText] = useState<FormType['text']>(MOCK_DATA.text);
  const [photos, setPhotos] = useState<FormType['photos']>(MOCK_DATA.photos);

  const [sentFormObject, setSentFormObject] = useState<FormType | null>(null);

  const handleTitleChange = useCallback<ChangeEventHandler<HTMLInputElement>>(
    e => setTitle(e.target.value),
    [setTitle],
  );
  const handleTextChange = useCallback<ChangeEventHandler<HTMLTextAreaElement>>(
    e => setText(e.target.value),
    [setText],
  );
  const handleFormSubmit = useCallback<FormEventHandler<HTMLFormElement>>((e) => {
    e.preventDefault();
    setSentFormObject({
      title,
      text,
      photos,
    });
  }, [title, text, photos, setSentFormObject]);

  const [theme, setTheme] = useState<'light' | 'dark'>('light');

  const handleThemeChange = useCallback<ChangeEventHandler<HTMLInputElement>>(e => {
    setTheme(e.target.checked ? 'light' : 'dark');
  }, [setTheme]);

  useEffect(() => {
    document.body.classList.remove('theme--light');
    document.body.classList.remove('theme--dark');
    document.body.classList.add(`theme--${theme}`);
  }, [theme]);

  return (
    <div className={st.app}>
      <header className={st.header}>
        <h1 className={st.viewTitle}>New blog post</h1>
        <Toggle
          checked={theme === 'light'}
          className={st.themeToggle}
          icons={{
            checked: <img src={sunImage} width="16" height="16"/>,
            unchecked: <img src={moonImage} width="14" height="14"/>,
          }}
          onChange={handleThemeChange}
        />
      </header>

      {!sentFormObject && (
        <form className={st.form} onSubmit={handleFormSubmit}>
          <div className={st.field}>
            <label className={st.label} htmlFor="title">Title</label>
            <input
              className={st.input}
              type="text"
              id="title"
              value={title}
              onChange={handleTitleChange}
            />
          </div>

          <div className={st.field}>
            <label className={st.label} htmlFor="text">Text</label>
            <textarea
              className={st.input}
              id="text"
              rows={10}
              value={text}
              onChange={handleTextChange}
            />
          </div>

          <div className={st.field}>
            <label className={st.label}>Photos</label>
            <FileUploader
              uploaderClassName={st.fileUploader}
              files={photos}
              onChange={setPhotos}
              theme={theme}
            />
          </div>

          <div className={st.field}>
            <button className={st.button} type="submit">Publish</button>
          </div>
        </form>
      )}

      {!!sentFormObject && (
        <pre className={st.result}>
          <code>
            {JSON.stringify(sentFormObject, null, 2)}
          </code>
        </pre>
      )}
    </div>
  );
}
