// examples/svelte-uploader/minimal/App.svelte
<script>
  import * as LR from "@uploadcare/blocks";
  LR.registerBlocks(LR);
</script>

<main>
  <div>
  <lr-config ctx-name="my-uploader" pubkey="2b7f257e8ea0817ba746">
  </lr-config>
  <lr-file-uploader-minimal
    css-src="https://cdn.jsdelivr.net/npm/@uploadcare/blocks@0.30.0/web/lr-file-uploader-minimal.min.css"
    ctx-name="my-uploader">
  </lr-file-uploader-minimal>
</div>
</main>

// examples/vue-uploader/minimal/src/App.vue
<script setup lang="ts">
import * as LR from "@uploadcare/blocks";

LR.registerBlocks(LR);
</script>

<template>
  <div>
    <lr-config ctx-name="my-uploader" pubkey="2b7f257e8ea0817ba746"></lr-config>
    <lr-file-uploader-minimal
      css-src="https://cdn.jsdelivr.net/npm/@uploadcare/blocks@0.30.0/web/lr-file-uploader-minimal.min.css"
      ctx-name="my-uploader"
      class="my-config"
    ></lr-file-uploader-minimal>
  </div>
</template>
